repo_url: https://github.com/Requisitos-de-Software/2025.1-FGTS/tree/main
repo_name: 2025.1-FGTS

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.keys

site_name: FGTS

theme:
  name: material
  favicon: assets/logo_fgts.png
  logo: assets/logo_fgts.png
  features:
    - navigation.instant
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/weather-night
        name: Escuro

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Claro

  language: pt-BR

extra_css: [stylesheets/extra.css]

nav:
  - Home: index.md
  - Atas de Reunião:
    - Ata 1 (07/04): atas/ata_07_04.md
    - Ata 2 (11/04): atas/ata_11_04.md
    - Ata 3 (25/04): atas/ata_25_04.md
    - Ata 4 (01/05): atas/ata_01_05.md
    - Ata 4.1 (02/05): atas/ata_02_05.md
  - Planejamento:
    - Aplicativo: Planejamento/Aplicativo.md
    - Cronograma: Planejamento/Cronograma.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Metodologia: Planejamento/Metodologia.md
    - Plano de Reuniões: Planejamento/Plano-de-Reunioes.md
  - Entregas:
    - Entrega 1: Entregas/Entrega-1.md
  - Inspeção +1:
    - Entrega 1: Inspecao-mais1/Entrega-1.md
  - Pré-Rastreabilidade:
    - Rich Picute: Pre-Rastreabilidade/Rich-Picture.md
  - Elicitação:
    - Perfil de Usuário: Elicitacao/Perfil-de-Usuario.md
    - Definição de Personas: Elicitacao/Definicao-de-Personas.md
    - Técnicas de Elicitação:
      - Entrevista: Elicitacao/Tecnicas-de-Elicitacao/Entrevista.md
      - Instrospecção: Elicitacao/Tecnicas-de-Elicitacao/Introspeccao.md
      - Observação: Elicitacao/Tecnicas-de-Elicitacao/Observacao.md
      - Storytelling: Elicitacao/Tecnicas-de-Elicitacao/Storytelling.md
    - Técnicas de Priorização:
      - First Things First: Elicitacao/Tecnicas-de-Priorizacao/First-Things-First.md
      - In or Out: Elicitacao/Tecnicas-de-Priorizacao/In-or-Out.md
      - Three-Level Scale: Elicitacao/Tecnicas-de-Priorizacao/Three-Level-Scale.md
      - $100 Test: Elicitacao/Tecnicas-de-Priorizacao/100-Test.md
  